version: '3'

services: 

  mysql: 
    build: ./.docker/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adonis
    networks:
      - net_adonis

networks:
  net_adonis:
    driver: bridge